config/routes.rb
Rails.application.routes.draw do
  
  resources :tasks
  root 'tasks#index'
  patch '/tasks/:id/toggle_status', to: 'tasks#toggle_status', as: :toggle_status_task
  
  resources :users 
  get  '/signup',  to: 'users#new'
  
  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  validates :name, presence: true, length: { maximum: 30 }
  validates :body, presence: true, length: { maximum: 100 } 
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks
  validates :name, presence: true, length: { maximum: 30 }
  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(name: params[:session][:name])
    if @user && @user.authenticate(params[:session][:password])
      log_in(@user)
      redirect_to root_url
    else
      flash.now[:danger] = '名前とパスワードの組み合わせが正しくありません'
      render 'new'
    end
  end
  
  def destroy
    log_out
    flash[:warning] = 'ログアウトしました'
    redirect_to root_url
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  def index
    # @tasks = Task.all
    @task_todo = Task.where(flag: 0)
    @task_done = Task.where(flag: 1)
    @task = Task.new
  end

  # GET /tasks/1
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  def create
    @task_todo = Task.where(flag: 0)
    @task_done = Task.where(flag: 1)
    @task = current_user.tasks.build(task_params)
    if @task.save
      flash[:success] = "作成しました"
      redirect_to root_url
    else
      # flash[:danger] = "作成できませんでした"
      render :index
    end
  end

  # PATCH/PUT /tasks/1
  def update
    if @task.update(task_params)
      # format.html { redirect_to tasks_path, notice: 'success : 更新しました' }
      flash[:success] = "更新しました"
      redirect_to '/'
    else
      render :edit
    end
  end

  # DELETE /tasks/1
  def destroy
    @task.destroy
    redirect_to tasks_url, notice: 'Task was successfully destroyed.' 
  end

  # PATCH /tasks/1/toggle_status
  def toggle_status
    @task = Task.find(params[:id])
    if @task.flag == 0
      @task.update_attribute(:flag, 1)
    else
      @task.update_attribute(:flag, 0)
    end
    flash[:success] = "更新しました"
    redirect_to '/'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :body, :flag)
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
    @tasks = @user.tasks  #ユーザーと紐づけられたタスク
    @task_todo = Task.where("flag = ? and user_id = ?", 0, params[:id])  
    # @task_todo = @tasks.where(flag:0)  #上に同義
    @task_done = Task.where("flag = ? and user_id = ?", 1, params[:id]) 
    # @task_done = @tasks.where(flag: 1)  #上に同義
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "ユーザー登録が完了しました"
      # log_in(@user)
      redirect_to root_url
    else
      # flash[:danger] = "失敗しました"
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # 現在ログイン中のユーザーを返す (いる場合)
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end
  
  # 現在のユーザーをログアウトする
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse">
  <%= link_to "TODOアプリ", root_path, id: "logo" %>
  <nav>
    <ul class="nav navbar-nav navbar-right">
      <% if logged_in? %>
        <li><%= link_to "ログインユーザー：#{current_user.name}", user_path(current_user.id) %></li>
        <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "ログイン", login_path %></li>
        <li><%= link_to "新規ユーザー登録", signup_path %></li>
      <% end %>
      <li><%= link_to "ユーザー登録者一覧", users_path %></li>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kadai2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>
        </div>
      </div>
      <%= yield %>
      <%#= debug(params) if Rails.env.development? %>
    </main>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <!--The form contains <%= pluralize(@user.errors.count, "error") %>.-->
      登録できませんでした
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_task_list.html.erb
<div class="index-page__tasks">
  
  <div class="index-page__task-list">
    <h2>TODO</h2>
    <% @task_todo.each do |task| %>
      <table class='task_table'>
        <tr>
          <th>担当者</th><td><%= task.name %></td>
        </tr>
        <tr>
          <th>内容</th><td><%= task.body %></td>
        </tr>
        <% if logged_in? %>
          <tr>
            <td colspan='2' class="task_buttons">
              <span><%= link_to '編集', edit_task_path(task), class: "btn btn-default btn-sm" %></span>
              <!--<%= link_to 'Destroy', task_path(task), method: :delete %>-->
              <span><%= link_to 'DONEにする', toggle_status_task_path(task), method: :patch, 
                                                                              class: "btn btn-default btn-sm" %></span>
            </td>
          </tr>
        <% end %>
      </table>       
    <% end %>
  </div>
  
  <div class="index-page__task-list">
    <h2>DONE</h2>
    <% @task_done.each do |task| %>
      <table class='task_table'>
        <tr>
          <th>担当者</th><td><%= task.name %></td>
        </tr>
        <tr>
          <th>内容</th><td><%= task.body %></td>
        </tr>
        <% if logged_in? %>
          <tr>
            <td colspan='2' class="task_buttons">
              <span><%= link_to '編集', edit_task_path(task), class: "btn btn-default btn-sm" %></span>
              <span><%= link_to 'TODOにする', toggle_status_task_path(task), method: :patch, 
                                                                              class: "btn btn-default btn-sm" %></span>
            </td>
          </tr>
        <% end %>
      </table>       
    <% end %>
  </div>
</div>

app/views/tasks/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    
    <%= form_with(model: task, local: true, class: "index-page__form") do |form| %>
      <% if task.errors.any? %>
        <div id="error_explanation">
          <div class="alert alert-danger">
            <!--The form contains <%= pluralize(task.errors.count, "error") %>.-->
            <%= yield(:btn_name) %>できませんでした
          </div>
          <ul>
          <% task.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
  
      <%= form.label :name, "Name（担当者）" %>
      <%= form.text_field :name, class: 'form-control' %>
  
      <%= form.label :body, "Body（内容）" %>
      <%= form.text_area :body, class: 'form-control' %>
  
      <!--<%= form.hidden_field :user_id, :value => "#{current_user.id}" %>-->
      <%= hidden_field_tag :user_id, current_user.id %>  <!--  ここ   --!>
      <%= form.submit yield(:btn_name), class: "btn btn-primary"%>
    <% end %>
    
  </div>
</div>

app/views/tasks/edit.html.erb
<% provide(:btn_name, "更新") %>

<!--<h1>Editing Task</h1>-->

<%= render 'form', task: @task %>

<%#= link_to 'Show', @task %> 
<%#= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<% provide(:btn_name, "作成") %>

<!--<p id="notice"><%#= notice %></p>-->

<!--<h1>TODOアプリ</h1>-->
<% if logged_in? %>
  <%= render 'form', task: @task %>
<% end %>
<%= render 'shared/task_list' %>

app/views/tasks/new.html.erb
<% provide(:name, "作成") %>

<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @task.body %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/users/index.html.erb
<h1>ユーザー登録者一覧</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>ユーザー登録</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "登録する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %>　が登録したタスク一覧</h1>
<%= render 'shared/task_list' %>